### PR TITLE
Update gradle dependencies.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Fix AndroidManifest.xml.

### CODE REVIEW

**Comment by nenick** [comment]
Hey thanks for your upgrade effort.

Current I'm working on upgrades and tool changes too on another branch https://github.com/nenick/android-gradle-template/tree/rewrite

I can't take all your changes current. This would break some stuff like robolectric tests because 'com.android.support:support-v4:23.0.0' isn't good supported yet. We need also some changes at .travis.yml to support the new tools versions.

**Comment by IgorGanapolsky** [comment]
OK.  Does that mean developers cannot use support-lib 23 if they wish to
use Robolectric?

Igor

**Comment by nenick** [comment]
Indeed they can't use robolectric 3.0 if they will use support-v23 but they are working on it https://github.com/robolectric/robolectric/issues/1865

Did you try the robolectric tests after your upgrades? Without upgrading the .travis.yml we get no automated report about it

**Comment by IgorGanapolsky** [comment]
Yes, unfortunately the Robolectric tests don't work in my end...

Thanks,
Igor

**Comment by nenick** [comment]
I took all dependency upgrades into the https://github.com/nenick/android-gradle-template/tree/rewrite branch which work without issues. Support v22 is the current max when using robolectric. I will replace the master by the branch when the rewrite is done.

**Pull request closed without merging**
