### PR TITLE
Make adb wait as much as needed instead of blocking the build for a minute preventively

### PR DESCRIPTION
**Pull request by bluehallu**

### CODE REVIEW

**Comment by nenick** [comment]
Thank you for this solution! This looks much better than the sleep command.

**Comment by bluehallu** [comment]
@nenick As much as I clearly prefer this solution, I'm now not entirely convinced it works all the time, I had a failure due to the usual shellUnresponsive exception with this approach. I increased the delay even further and it hasn't complained so far, but it really should have never needed more than 60 seconds if that was producing stable builds on your approach right?

**Comment by nenick** [comment]
This 60 seconds results in very rare ShellCommandUnresponsiveException. Only one build from about 30 failed.

**Comment by bluehallu** [comment]
well, please let me know if this approach works better or not then :)

**Comment by nenick** [comment]
Looks like the line `om.android.ddmlib.DdmPreferences.setTimeOut(240000)` has no effect
 because appIt:connectedCheck failed after 40 seconds with ShellCommandUnresponsiveException

**Comment by bluehallu** [comment]
@nenick From what I'm seeing in my own builds, it does make a difference since without it, it will crash 100% of the time, but it still isn't reliable. Tried with the new adbOptions syntax from the gradle helper v1.2 and makes no difference either. I recommend you roll this back until the bug is sorted.

**Comment by nenick** [comment]
I think we must create a new issue or it will not be fixed. One comment say it work with android gradle plugin 1.1 but not anymore with 1.2
https://code.google.com/p/android/issues/list?can=1&q=DdmPreferences&colspec=ID+Type+Status+Owner+Summary+Stars&cells=tiles

**Pull request merged**
